CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    token_version BIGINT NOT NULL,
    minor BOOLEAN NOT NULL,
    guardian_contact VARCHAR(255),
    consent_on_file BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_user_account PRIMARY KEY (id),
    CONSTRAINT uk_user_account_email UNIQUE (email),
    CONSTRAINT ck_user_account_role CHECK (role IN ('MUSICIAN', 'ADMIN')),
    CONSTRAINT ck_user_account_status CHECK (status IN ('PENDING', 'ACTIVE', 'DEACTIVATED')),
    CONSTRAINT ck_user_account_token_version CHECK (token_version >= 0),
    CONSTRAINT ck_user_account_minor_fields CHECK (
        (minor AND guardian_contact IS NOT NULL AND BTRIM(guardian_contact) <> '' AND consent_on_file)
        OR (NOT minor AND guardian_contact IS NULL AND NOT consent_on_file)
    )
);

CREATE TABLE password_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_password_token PRIMARY KEY (id),
    CONSTRAINT uk_password_token_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_token_type CHECK (type IN ('ACTIVATION', 'RESET')),
    CONSTRAINT ck_password_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT fk_password_token_user FOREIGN KEY (user_id) REFERENCES user_account (id)
);

CREATE TABLE admin_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    admin_id BIGINT NOT NULL,
    permission VARCHAR(255) NOT NULL,
    CONSTRAINT pk_admin_permission PRIMARY KEY (id),
    CONSTRAINT uk_admin_permission_admin_permission UNIQUE (admin_id, permission),
    CONSTRAINT ck_admin_permission_permission CHECK (permission IN (
        'MANAGE_USERS',
        'MANAGE_ADMIN_ROLES',
        'MANAGE_GROUPS',
        'MANAGE_SHEET_MUSIC',
        'MANAGE_EVENTS',
        'MANAGE_CONTENT'
    )),
    CONSTRAINT fk_admin_permission_admin FOREIGN KEY (admin_id) REFERENCES user_account (id)
);

CREATE TABLE band_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_band_group PRIMARY KEY (id)
);

CREATE TABLE musician_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    musician_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT pk_musician_group PRIMARY KEY (id),
    CONSTRAINT uk_musician_group_musician_group UNIQUE (musician_id, group_id),
    CONSTRAINT fk_musician_group_musician FOREIGN KEY (musician_id) REFERENCES user_account (id),
    CONSTRAINT fk_musician_group_group FOREIGN KEY (group_id) REFERENCES band_group (id)
);

CREATE TABLE collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_collection PRIMARY KEY (id)
);

CREATE TABLE sheet_music (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    composer VARCHAR(255),
    collection_id BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255),
    content_type VARCHAR(255),
    all_scope BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_sheet_music PRIMARY KEY (id),
    CONSTRAINT uk_sheet_music_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_sheet_music_collection FOREIGN KEY (collection_id) REFERENCES collection (id)
);

CREATE TABLE sheet_group_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sheet_music_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT pk_sheet_group_access PRIMARY KEY (id),
    CONSTRAINT uk_sheet_group_access_sheet_group UNIQUE (sheet_music_id, group_id),
    CONSTRAINT fk_sheet_group_access_sheet FOREIGN KEY (sheet_music_id) REFERENCES sheet_music (id),
    CONSTRAINT fk_sheet_group_access_group FOREIGN KEY (group_id) REFERENCES band_group (id)
);

CREATE TABLE sheet_musician_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sheet_music_id BIGINT NOT NULL,
    musician_id BIGINT NOT NULL,
    CONSTRAINT pk_sheet_musician_access PRIMARY KEY (id),
    CONSTRAINT uk_sheet_musician_access_sheet_musician UNIQUE (sheet_music_id, musician_id),
    CONSTRAINT fk_sheet_musician_access_sheet FOREIGN KEY (sheet_music_id) REFERENCES sheet_music (id),
    CONSTRAINT fk_sheet_musician_access_musician FOREIGN KEY (musician_id) REFERENCES user_account (id)
);

CREATE TABLE event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    location VARCHAR(255),
    starts_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    is_public BOOLEAN NOT NULL,
    all_scope BOOLEAN NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT ck_event_status CHECK (status IN ('SCHEDULED', 'CANCELLED'))
);

CREATE TABLE event_group_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT pk_event_group_access PRIMARY KEY (id),
    CONSTRAINT uk_event_group_access_event_group UNIQUE (event_id, group_id),
    CONSTRAINT fk_event_group_access_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_event_group_access_group FOREIGN KEY (group_id) REFERENCES band_group (id)
);

CREATE TABLE event_musician_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    musician_id BIGINT NOT NULL,
    CONSTRAINT pk_event_musician_access PRIMARY KEY (id),
    CONSTRAINT uk_event_musician_access_event_musician UNIQUE (event_id, musician_id),
    CONSTRAINT fk_event_musician_access_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_event_musician_access_musician FOREIGN KEY (musician_id) REFERENCES user_account (id)
);

CREATE TABLE album (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_album PRIMARY KEY (id)
);

CREATE TABLE photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    album_id BIGINT NOT NULL,
    caption VARCHAR(255),
    storage_key VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_photo PRIMARY KEY (id),
    CONSTRAINT fk_photo_album FOREIGN KEY (album_id) REFERENCES album (id)
);

CREATE TABLE news_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_news_post PRIMARY KEY (id)
);

CREATE TABLE video_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_video_link PRIMARY KEY (id)
);

CREATE TABLE course_announcement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    start_date DATE NOT NULL,
    end_date DATE,
    price NUMERIC(10, 2) NOT NULL,
    instrument VARCHAR(255) NOT NULL,
    minimum_age INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    version BIGINT,
    CONSTRAINT pk_course_announcement PRIMARY KEY (id),
    CONSTRAINT ck_course_announcement_price CHECK (price >= 0),
    CONSTRAINT ck_course_announcement_minimum_age CHECK (minimum_age >= 0)
);

CREATE TABLE contact_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_contact_submission PRIMARY KEY (id)
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    actor_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BIGINT NOT NULL,
    timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    details VARCHAR(255),
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);

CREATE INDEX idx_user_account_role_status ON user_account (role, status);
CREATE INDEX idx_password_token_user_unused ON password_token (user_id) WHERE used_at IS NULL;
CREATE INDEX idx_musician_group_group ON musician_group (group_id);
CREATE INDEX idx_sheet_music_collection ON sheet_music (collection_id);
CREATE INDEX idx_sheet_group_access_group ON sheet_group_access (group_id);
CREATE INDEX idx_sheet_musician_access_musician ON sheet_musician_access (musician_id);
CREATE INDEX idx_event_public_starts_at ON event (starts_at) WHERE is_public;
CREATE INDEX idx_event_group_access_group ON event_group_access (group_id);
CREATE INDEX idx_event_musician_access_musician ON event_musician_access (musician_id);
CREATE INDEX idx_photo_album_id ON photo (album_id, id);
CREATE INDEX idx_news_post_published_at ON news_post (published_at DESC);
CREATE INDEX idx_video_link_created_at ON video_link (created_at DESC);
CREATE INDEX idx_course_announcement_start_date ON course_announcement (start_date);
CREATE INDEX idx_audit_log_entity_history
    ON audit_log (entity_type, entity_id, timestamp DESC, id DESC);
