CREATE TABLE pending_file_deletion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    storage_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_pending_file_deletion PRIMARY KEY (id),
    CONSTRAINT uk_pending_file_deletion_storage_key UNIQUE (storage_key)
);

CREATE INDEX idx_pending_file_deletion_created_at ON pending_file_deletion (created_at, id);
