package com.banda.groups;

import com.banda.security.AdminPermission;
import com.banda.security.AdminPermissionRepository;
import com.banda.security.Permission;
import com.banda.support.IntegrationTestBase;
import com.banda.users.UserAccount;
import com.banda.users.UserAccountRepository;
import com.banda.users.UserRole;
import com.banda.users.UserStatus;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.time.Instant;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;

/**
 * Real-Postgres, real-thread proof of the "delete in-use group" TOCTOU backstop
 * {@link GroupService#delete}'s own Javadoc claims: the actual {@code musician_group.group_id}
 * foreign key (RESTRICT semantics, no cascade — see {@link MusicianGroup}'s Javadoc) genuinely
 * exists and genuinely rejects a concurrent delete when a member is assigned between the
 * up-front {@code existsByGroup} check and the actual delete/flush. {@link GroupServiceTest}
 * only proves the reaction to a Mockito-stubbed {@code DataIntegrityViolationException} —
 * never that the real schema (generated by {@code ddl-auto: update}, no versioned migration
 * exists for this project) actually has this constraint and actually fires it.
 *
 * <p>Unlike {@code com.banda.security.PermissionServiceIntegrationTest}'s symmetric race (two
 * identical calls racing a shared {@link java.util.concurrent.CyclicBarrier}), this race needs
 * precise interleaving between two DIFFERENT operations — the up-front check must observe
 * "no members" before the concurrent assignment commits, but the actual delete must observe
 * "a member exists" after it. A bare barrier cannot guarantee that ordering deterministically,
 * so this test adds one narrow, test-only synchronization seam: a JDK dynamic proxy in front
 * of the real {@link MusicianGroupRepository} bean that pauses the delete thread for exactly
 * the width of {@code existsByGroup}'s return, letting the assign thread run to completion (a
 * real, committed insert) before the delete thread's own {@code delete()}/{@code flush()}
 * calls proceed — at which point the real FK constraint is what rejects it, not test code.
 */
@Import(GroupServiceDeleteRaceIntegrationTest.RaceSyncConfig.class)
class GroupServiceDeleteRaceIntegrationTest extends IntegrationTestBase {

    @Autowired
    private GroupService groupService;

    @Autowired
    private GroupRepository groupRepository;

    @Autowired
    @Qualifier("musicianGroupRepository")
    private MusicianGroupRepository realMusicianGroupRepository;

    @Autowired
    private UserAccountRepository userAccountRepository;

    @Autowired
    private AdminPermissionRepository adminPermissionRepository;

    @Test
    void concurrentAssignBetweenTheUpFrontCheckAndTheActualDeleteIsRejectedByTheRealForeignKeyConstraint() throws Exception {
        UserAccount admin = userAccountRepository.saveAndFlush(
                new UserAccount("race-delete-admin@example.com", UserRole.ADMIN, UserStatus.ACTIVE, Instant.now()));
        adminPermissionRepository.saveAndFlush(new AdminPermission(admin, Permission.MANAGE_GROUPS));
        Group group = groupRepository.saveAndFlush(new Group("Race Group", null, Instant.now()));
        UserAccount musician = userAccountRepository.saveAndFlush(
                new UserAccount("race-delete-musician@example.com", UserRole.MUSICIAN, UserStatus.ACTIVE, Instant.now()));

        CountDownLatch checkPassed = new CountDownLatch(1);
        CountDownLatch assignCommitted = new CountDownLatch(1);
        RaceSyncConfig.checkPassedLatch = checkPassed;
        RaceSyncConfig.assignCommittedLatch = assignCommitted;

        ExecutorService executor = Executors.newFixedThreadPool(2);
        try {
            Future<Throwable> deleteOutcome = executor.submit(() ->
                    catchThrowable(() -> groupService.delete(admin, group.getId())));
            Future<Throwable> assignOutcome = executor.submit(() -> {
                checkPassed.await(5, TimeUnit.SECONDS);
                Throwable thrown = catchThrowable(() -> groupService.assignMusician(admin, group.getId(), musician.getId()));
                assignCommitted.countDown();
                return thrown;
            });

            Throwable deleteThrown = deleteOutcome.get(10, TimeUnit.SECONDS);
            Throwable assignThrown = assignOutcome.get(10, TimeUnit.SECONDS);

            assertThat(assignThrown)
                    .as("assignMusician itself must complete normally in this interleaving")
                    .isNull();
            assertThat(deleteThrown)
                    .as("the real FK constraint (RESTRICT, no cascade) must reject the delete once "
                            + "the concurrent assignment committed between the up-front check and the actual delete")
                    .isInstanceOf(GroupInUseException.class);

            assertThat(groupRepository.findById(group.getId()))
                    .as("the group must survive the rejected delete (rolled back, not half-applied)")
                    .isPresent();
            assertThat(realMusicianGroupRepository.existsByMusicianAndGroup(musician, group))
                    .as("the concurrent assignment must have actually persisted")
                    .isTrue();
        } finally {
            executor.shutdown();
            RaceSyncConfig.checkPassedLatch = null;
            RaceSyncConfig.assignCommittedLatch = null;
        }
    }

    @TestConfiguration
    static class RaceSyncConfig {

        static volatile CountDownLatch checkPassedLatch;
        static volatile CountDownLatch assignCommittedLatch;

        /**
         * Wraps the real {@code musicianGroupRepository} bean so {@link GroupService} (and
         * everything else in the context) transparently uses this proxy instead — {@code
         * @Primary} wins autowiring over the original bean. Every call is delegated to the
         * real repository untouched; only {@code existsByGroup} additionally pauses the
         * calling thread (the delete thread) after computing the real result, releasing the
         * assign thread and waiting for its real, committed insert before returning that
         * already-computed result back to {@link GroupService#delete}.
         */
        @Bean
        @Primary
        MusicianGroupRepository racingMusicianGroupRepository(
                @Qualifier("musicianGroupRepository") MusicianGroupRepository real) {
            return (MusicianGroupRepository) Proxy.newProxyInstance(
                    MusicianGroupRepository.class.getClassLoader(),
                    new Class<?>[]{MusicianGroupRepository.class},
                    (proxyInstance, method, args) -> {
                        Object result;
                        try {
                            result = method.invoke(real, args);
                        } catch (InvocationTargetException e) {
                            throw e.getCause();
                        }
                        if ("existsByGroup".equals(method.getName()) && checkPassedLatch != null) {
                            checkPassedLatch.countDown();
                            assignCommittedLatch.await(5, TimeUnit.SECONDS);
                        }
                        return result;
                    });
        }
    }
}
