server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: banda-app-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/banda}
    username: ${DB_USERNAME:banda}
    password: ${DB_PASSWORD:banda}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
